name: Publish binaries

on:
  release:
    types: [prereleased]

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew assemble
    - name: Pack
      run: chmod +x dist/*.sh && mv dist WeCross-Console && tar -zcvf WeCross-Console.tar.gz WeCross-Console
    - name: Checksum
      run: md5sum WeCross-Console.tar.gz > WeCross-Console.tar.gz.md5
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: WeCross-Console.tar.gz
        asset_name: WeCross-Console.tar.gz
        tag: ${{ github.ref }}
        overwrite: true

    - name: Upload checksum to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: WeCross-Console.tar.gz.md5
        asset_name: WeCross-Console.tar.gz.md5
        tag: ${{ github.ref }}
        overwrite: true
